In [3]:
import matplotlib.font_manager as fm

# fm.fontManager.ttflist
# # matplotlib only know these fonts
font_list = [f for f in fm.fontManager.ttflist]

# check font names what you want
cjk_list = ['CJK', 'Han', 'CN', 'TW']

for f in font_list:
    if any(s.lower() in f.name.lower() for s in cjk_list):
        print(f'name={f.name}, path={f.fname}')

name=STIXSizeTwoSym, path=c:\Users\tianl\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\mpl-data\fonts\ttf\STIXSizTwoSymBol.ttf
name=STIXSizeTwoSym, path=c:\Users\tianl\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\mpl-data\fonts\ttf\STIXSizTwoSymReg.ttf
name=Tw Cen MT Condensed, path=C:\Windows\Fonts\TCCM____.TTF
name=Tw Cen MT, path=C:\Windows\Fonts\TCBI____.TTF
name=Bradley Hand ITC, path=C:\Windows\Fonts\BRADHITC.TTF
name=Tw Cen MT Condensed Extra Bold, path=C:\Windows\Fonts\TCCEB.TTF
name=Elephant, path=C:\Windows\Fonts\ELEPHNT.TTF
name=Source Han Sans, path=C:\Users\tianl\AppData\Local\Microsoft\Windows\Fonts\SourceHanSans.ttc
name=Tw Cen MT, path=C:\Windows\Fonts\TCB_____.TTF
name=Elephant, path=C:\Windows\Fonts\ELEPHNTI.TTF
name=Tw Cen MT, path=C:\Windows\Fonts\TCMI____.TTF
name=Tw Cen MT Condensed, path=C:\Windows\Fonts\TCCB____.TTF
name=Tw Cen MT, path=C:\Windows\Fonts\TCM_____.TTF
name=Viner Hand ITC, path=C:\Windows\Fonts\VINERIT

In [1]:
import numpy as np

# 1. 创建一个示例三维数组
# 形状为 (A, B, C) -> (2, 3, 4)
arr_3d = np.arange(2 * 3 * 4).reshape((2, 3, 4))
print("原始数组形状:", arr_3d.shape)
print("原始数组:\n", arr_3d)

# 2. 轴调换 (Transpose)
# 将第1维(B)移动到最前面，原始的第0维(A)和第2维(C)跟在后面。
# 新的轴顺序是 (1, 0, 2)
# 形状从 (2, 3, 4) -> (3, 2, 4)
arr_transposed = arr_3d.transpose(1, 0, 2)
print("\n轴调换后形状:", arr_transposed.shape)
print("轴调换后数组:\n", arr_transposed)

# 3. 形状重塑 (Reshape)
# 保留第一个维度(B)，并将后面两个维度合并。
# 使用 -1 可以让Numpy/JAX自动计算合并后的维度大小 (2 * 4 = 8)
# 形状从 (3, 2, 4) -> (3, 8)
arr_flattened = arr_transposed.reshape((arr_3d.shape[1], -1))
print("\n最终展平后形状:", arr_flattened.shape)
print("最终展平后数组:\n", arr_flattened)

原始数组形状: (2, 3, 4)
原始数组:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

轴调换后形状: (3, 2, 4)
轴调换后数组:
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

最终展平后形状: (3, 8)
最终展平后数组:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
